[[emoji]]
match = "(?i:Bandwidth|expire|æµé‡|æ—¶é—´|åº”æ€¥|è¿‡æœŸ)"
emoji = "ğŸ³ï¸â€ğŸŒˆ"

[[emoji]]
match = "(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|é¦™æ¸¯|HK)"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "(?i:\\bTW[N]?\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b|TW)"
emoji = "ğŸ‡¨ğŸ‡³"

[[emoji]]
match = "(?i:\\bSG[P]?\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|SG)"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "(å°¼æ—¥åˆ©äºš|Nigeria)"
emoji = "ğŸ‡³ğŸ‡¬"

[[emoji]]
match = "(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|JP)"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "(?i:\\bK[O]?R\\b|Korea|é¦–å°”|éŸ©|éŸ“|KR)"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "(?i:\\bUS[A]?\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US)"
emoji = "ğŸ‡ºğŸ‡¸"

[[emoji]]
match = "(Ascension|é˜¿æ£®æ¾)"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emoji]]
match = "(?i:\\bUAE\\b|Dubai|é˜¿è”é…‹|è¿ªæ‹œ|AE|United Arab Emirates)"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emoji]]
match = "(é˜¿å°”å·´å°¼äºš|Albania|AL)"
emoji = "ğŸ‡¦ğŸ‡±"

[[emoji]]
match = "(Argentina|é˜¿æ ¹å»·|AR)"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "(Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³|AT)"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "(?i:\\bAU[S]?\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼|AU)"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "(é˜¿å¡æ‹œç–†|Azerbaijan|AZ)"
emoji = "ğŸ‡¦ğŸ‡¿"

[[emoji]]
match = "(æ³¢é»‘å…±å’Œå›½|æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³|Bosnia|Herzegovina|BA)"
emoji = "ğŸ‡§ğŸ‡¦"

[[emoji]]
match = "(Belgium|æ¯”åˆ©æ—¶|BE)"
emoji = "ğŸ‡§ğŸ‡ª"

[[emoji]]
match = "(ä¿åŠ åˆ©äºš|Bulgaria|BG)"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "(Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—|BR)"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶|CA)"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "(Switzerland|Zurich|ç‘å£«|è‹é»ä¸–|CH)"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "(æ™ºåˆ©|Chile|CL)"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "(Colombia|å“¥ä¼¦æ¯”äºš|CO)"
emoji = "ğŸ‡¨ğŸ‡´"

[[emoji]]
match = "(Costa Rica|å“¥æ–¯è¾¾é»åŠ |CR)"
emoji = "ğŸ‡¨ğŸ‡·"

[[emoji]]
match = "(å¡æµ¦è·¯æ–¯|Cyprus|CY)"
emoji = "ğŸ‡¨ğŸ‡¾"

[[emoji]]
match = "(Czech|æ·å…‹|CZ)"
emoji = "ğŸ‡¨ğŸ‡¿"

[[emoji]]
match = "(?i:\\bDE[U]?\\b|Germany|æ³•å…°å…‹ç¦|å¾·(å›½|æ„å¿—)|ä¸­å¾·|DE|^å¾·$)"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "(?i:\\bD[N]?K\\b|Denmark|ä¸¹éº¦|DK)"
emoji = "ğŸ‡©ğŸ‡°"

[[emoji]]
match = "(çˆ±æ²™å°¼äºš|Estonia|EE)"
emoji = "ğŸ‡ªğŸ‡ª"

[[emoji]]
match = "(åŸƒåŠ|Egypt|EG)"
emoji = "ğŸ‡ªğŸ‡¬"

[[emoji]]
match = "(?i:\\bES[P]?\\b|Spain|è¥¿ç­ç‰™|ES)"
emoji = "ğŸ‡ªğŸ‡¸"

[[emoji]]
match = "(Europe|æ¬§æ´²|EU)"
emoji = "ğŸ‡ªğŸ‡º"

[[emoji]]
match = "(Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº|FI)"
emoji = "ğŸ‡«ğŸ‡®"

[[emoji]]
match = "(?i:\\bFR[A]?\\b|France|Paris|æ³•å›½|å·´é»|FR)"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "(?i:\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦|UK)"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "(å¸Œè…Š|Greece|GR)"
emoji = "ğŸ‡¬ğŸ‡·"

[[emoji]]
match = "(æ ¼é²å‰äºš|Georgia|GE)"
emoji = "ğŸ‡¬ğŸ‡ª"

[[emoji]]
match = "(å…‹ç½—åœ°äºš|Croatia|HR)"
emoji = "ğŸ‡­ğŸ‡·"

[[emoji]]
match = "(Hungary|åŒˆç‰™åˆ©|HU)"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "(Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾|ID)"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—|IE)"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "(Israel|ä»¥è‰²åˆ—|IL)"
emoji = "ğŸ‡®ğŸ‡±"

[[emoji]]
match = "(é©¬æ©å²›|Mann|IM)"
emoji = "ğŸ‡®ğŸ‡²"

[[emoji]]
match = "(?i:\\bIN[D]?\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·|IN)"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "(ä¼Šæœ—|Iran|TR)"
emoji = "ğŸ‡®ğŸ‡·"

[[emoji]]
match = "(?i:\\bIS[L]?\\b|Iceland|å†°å²›|IS)"
emoji = "ğŸ‡®ğŸ‡¸"

[[emoji]]
match = "(Italy|Milan|æ„å¤§åˆ©|ç±³å…°|IT)"
emoji = "ğŸ‡®ğŸ‡¹"

[[emoji]]
match = "(çº¦æ—¦|Jordan|JO)"
emoji = "ğŸ‡¯ğŸ‡´"

[[emoji]]
match = "(è‚¯å°¼äºš|Kenya|KE)"
emoji = "ğŸ‡°ğŸ‡ª"

[[emoji]]
match = "(å‰å°”å‰æ–¯æ–¯å¦|Kyrgyzstan|KG)"
emoji = "ğŸ‡°ğŸ‡¬"

[[emoji]]
match = "(æŸ¬åŸ”å¯¨|Cambodia|KH)"
emoji = "ğŸ‡°ğŸ‡­"


[[emoji]]
match = "(North.*?Korea|æœé²œ|KP)"
emoji = "ğŸ‡°ğŸ‡µ"

[[emoji]]
match = "(å“ˆè¨å…‹æ–¯å¦|Kazakhstan|KZ)"
emoji = "ğŸ‡°ğŸ‡¿"

[[emoji]]
match = "(ç«‹é™¶å®›|Lietuvos|LT)"
emoji = "ğŸ‡±ğŸ‡¹"

[[emoji]]
match = "(å¢æ£®å ¡|Luxemburg|Luxembourg|LU)"
emoji = "ğŸ‡±ğŸ‡º"

[[emoji]]
match = "(æ‹‰è„±ç»´äºš|Latvia|LV)"
emoji = "ğŸ‡±ğŸ‡»"

[[emoji]]
match = "(Moldova|æ‘©å°”å¤šç“¦|MD)"
emoji = "ğŸ‡²ğŸ‡©"

[[emoji]]
match = "(åŒ—é©¬å…¶é¡¿|Macedonia|MK)"
emoji = "ğŸ‡²ğŸ‡°"

[[emoji]]
match = "(è’™å¤|ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ|Mongolia|MN)"
emoji = "ğŸ‡²ğŸ‡³"

[[emoji]]
match = "(Macao|æ¾³é—¨|\\bCTM\\b|MO)"
emoji = "ğŸ‡²ğŸ‡´"

[[emoji]]
match = "(å¢¨è¥¿å“¥|Mexico|MX)"
emoji = "ğŸ‡²ğŸ‡½"

[[emoji]]
match = "(Malaysia|é©¬æ¥|MY)"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "(?i:\\bNL[D]?\\b|Netherlands|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹|NL)"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "(æŒªå¨|Norway|NO)"
emoji = "ğŸ‡³ğŸ‡´"

[[emoji]]
match = "(æ–°è¥¿å…°|çº½è¥¿å…°|New Zealand|NZ)"
emoji = "ğŸ‡³ğŸ‡¿"

[[emoji]]
match = "(Philippines|è²å¾‹å®¾|PH)"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "(Pakistan|å·´åŸºæ–¯å¦|PK)"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "(?i:\\bP[O]?L\\b|Poland|æ³¢å…°|PL)"
emoji = "ğŸ‡µğŸ‡±"

[[emoji]]
match = "(å·´æ‹¿é©¬|Panama|PA)"
emoji = "ğŸ‡µğŸ‡¦"

[[emoji]]
match = "(ç§˜é²|Peru|PE)"
emoji = "ğŸ‡µğŸ‡ª"

[[emoji]]
match = "(è‘¡è„ç‰™|Portugal|PT)"
emoji = "ğŸ‡µğŸ‡¹"

[[emoji]]
match = "(Romania|ç½—é©¬å°¼äºš|RO)"
emoji = "ğŸ‡·ğŸ‡´"

[[emoji]]
match = "(å¡å°”ç»´äºš|Serbia|RS)"
emoji = "ğŸ‡·ğŸ‡¸"

[[emoji]]
match = "(?i:\\bRU[S]?\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„|RU)"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "(Arabia|æ²™ç‰¹|SA)"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emoji]]
match = "(Sweden|ç‘å…¸|SE)"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "(æ–¯æ´›æ–‡å°¼äºš|Slovenia|SI)"
emoji = "ğŸ‡¸ğŸ‡®"

[[emoji]]
match = "(æ–¯æ´›ä¼å…‹|Slovensko|SK)"
emoji = "ğŸ‡¸ğŸ‡°"

[[emoji]]
match = "(Thailand|æ³°å›½|æ›¼è°·|TH)"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "(çªå°¼æ–¯|Tunisia|TN)"
emoji = "ğŸ‡¹ğŸ‡³"

[[emoji]]
match = "(Turkey|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”|TR)"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "(ä¹Œæ‹‰åœ­|Uruguay|UV)"
emoji = "ğŸ‡ºğŸ‡¾"

[[emoji]]
match = "(Vietnam|è¶Šå—|VN)"
emoji = "ğŸ‡»ğŸ‡³"

[[emoji]]
match = "(Africa|å—é|ZA)"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emoji]]
match = "(Ukraine|UA|ä¹Œå…‹å…°)"
emoji = "ğŸ‡ºğŸ‡¦"

[[emoji]]
match = "(Puerto.*?Rico|æ³¢å¤šé»å„|PR)"
emoji = "ğŸ‡µğŸ‡·"

[[emoji]]
match = "(Ecuador|å„ç“œå¤šå°”|EC)"
emoji = "ğŸ‡ªğŸ‡¨"


[[emoji]]
match = "(Morocco|æ‘©æ´›å“¥|MA)"
emoji = "ğŸ‡²ğŸ‡¦"


[[emoji]]
match = "(Nepal|å°¼æ³Šå°”|NP)"
emoji = "ğŸ‡³ğŸ‡µ"


[[emoji]]
match = "(Bengal|å­ŸåŠ æ‹‰|BD)"
emoji = "ğŸ‡§ğŸ‡©"

[[emoji]]
match = "(?i:\\bC[H]?N\\b|China|back|å›å›½|ä¸­å›½[^-]|æ±Ÿè‹[^-]|åŒ—äº¬[^-]|ä¸Šæµ·[^-]|å¹¿å·[^-]|æ·±åœ³[^-]|æ­å·[^-]|å¸¸å·[^-]|å¾å·[^-]|é’å²›[^-]|å®æ³¢[^-]|é•‡æ±Ÿ[^-]|æˆéƒ½[^-]|æ²³åŒ—[^-]|å±±è¥¿[^-]|è¾½å®[^-]|å‰æ—[^-]|é»‘é¾™æ±Ÿ[^-]|æ±Ÿè‹[^-]|æµ™æ±Ÿ[^-]|å®‰å¾½[^-]|ç¦å»º[^-]|æ±Ÿè¥¿[^-]|å±±ä¸œ[^-]|æ²³å—[^-]|æ¹–åŒ—[^-]|æ¹–å—[^-]|å¹¿ä¸œ[^-]|æµ·å—[^-]|å››å·[^-]|è´µå·[^-]|äº‘å—[^-]|é™•è¥¿[^-]|ç”˜è‚ƒ[^-]|é’æµ·[^-]|å†…è’™å¤[^-]|å¹¿è¥¿[^-]|è¥¿è—[^-]|å®å¤[^-]|æ–°ç–†[^-])"
emoji = "ğŸ‡¨ğŸ‡³"
